In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

In [35]:
import seaborn as sns

In [37]:
df = pd.read_csv('Churn_Modelling.csv')

In [39]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [41]:
#step 2
X = df.drop(['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)  # Remove unnecessary columns
y = df['Exited']

In [43]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [45]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [47]:
le_gender = LabelEncoder()
X['Gender'] = le_gender.fit_transform(X['Gender'])

le_geo = LabelEncoder()
X['Geography'] = le_geo.fit_transform(X['Geography'])

In [49]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64
9996,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,0,0,36,7,0.00,1,0,1,42085.58
9998,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,0,0,28,4,130142.79,1,1,0,38190.78

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [55]:
model = Sequential()

In [57]:
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))  # Using ReLU activation
# Hidden Layer
model.add(Dense(32, activation='relu'))  # You can experiment with other activations here (sigmoid, tanh, etc.)
# Output Layer
model.add(Dense(1, activation='sigmoid'))  # Sigmoid for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=30, batch_size=32, validation_data=(X_test_scaled, y_test))

# Step 5: Evaluate the model and print accuracy score and confusion matrix
y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)

Epoch 1/30

C:\Users\Armaan\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7932 - loss: 0.4940 - val_accuracy: 0.8330 - val_loss: 0.4071
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.8323 - loss: 0.4079 - val_accuracy: 0.8435 - val_loss: 0.3756
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.8537 - loss: 0.3665 - val_accuracy: 0.8570 - val_loss: 0.3592
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.8558 - loss: 0.3542 - val_accuracy: 0.8570 - val_loss: 0.3538
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8670 - loss: 0.3327 - val_accuracy: 0.8560 - val_loss: 0.3512
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8591 - loss: 0.3431 - val_accuracy: 0.8560 - val_loss: 0.3505
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8606 - loss: 0.3299 - val_accuracy: 0.8570 - val_loss: 0.3478
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8593 - loss: 0.3443 - val_accuracy: 0.8570 - val_loss: 0.3440
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8627 - loss: 0.3340 - val_accuracy: 0.8575 - val_loss: 0.3469
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8648 - loss: 0.3214 - val_accuracy: 0.8615 - val_loss: 0.3422
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8676 - loss: 0.3237 - val_accuracy: 0.8595 - val_loss: 0.3440
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8666 - loss: 0.3265 - val_accuracy: 0.8610 - val_loss: 0.3414
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8685 - loss: 0.3197 - val_accuracy: 0.8600 - val_loss: 0.3403
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8703 - loss: 0.3187 - val_accuracy: 0.8525 - val_loss: 0.3473
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8758 - loss: 0.3121 - val_accuracy: 0.8575 - val_loss: 0.3430
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8630 - loss: 0.3257 - val_accuracy: 0.8560 - val_loss: 0.3418
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8691 - loss: 0.3150 - val_accuracy: 0.8565 - val_loss: 0.3458
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8708 - loss: 0.3117 - val_accuracy: 0.8600 - val_loss: 0.3415
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8658 - loss: 0.3174 - val_accuracy: 0.8595 - val_loss: 0.3410
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8709 - loss: 0.3115 - val_accuracy: 0.8560 - val_loss: 0.3445
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8751 - loss: 0.2981 - val_accuracy: 0.8555 - val_loss: 0.3414
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8778 - loss: 0.2998 - val_accuracy: 0.8635 - val_loss: 0.3442
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.8757 - loss: 0.3103 - val_accuracy: 0.8590 - val_loss: 0.3402
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8773 - loss: 0.2983 - val_accuracy: 0.8560 - val_loss: 0.3446
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8692 - loss: 0.3112 - val_accuracy: 0.8610 - val_loss: 0.3402
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8780 - loss: 0.2935 - val_accuracy: 0.8535 - val_loss: 0.3461
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8806 - loss: 0.2956 - val_accuracy: 0.8560 - val_loss: 0.3438
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8754 - loss: 0.2965 - val_accuracy: 0.8545 - val_loss: 0.3486
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8811 - loss: 0.2958 - val_accuracy: 0.8590 - val_loss: 0.3456
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.8694 - loss: 0.3054 - val_accuracy: 0.8545 - val_loss: 0.3454
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [58]:
# Accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100}%")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 85.45%
Confusion Matrix:
[[1515   92]
 [ 199  194]]

In [29]:
model_tanh = Sequential()
model_tanh.add(Dense(64, input_dim=X_train.shape[1], activation='tanh'))
model_tanh.add(Dense(32, activation='tanh'))
model_tanh.add(Dense(1, activation='sigmoid'))
model_tanh.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_tanh.fit(X_train_scaled, y_train, epochs=20, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluating model with 'tanh'
y_pred_tanh = (model_tanh.predict(X_test_scaled) > 0.5).astype(int)
accuracy_tanh = accuracy_score(y_test, y_pred_tanh)
print(f"Accuracy with Tanh activation: {accuracy_tanh * 100:.2f}%")

Epoch 1/20

C:\Users\Armaan\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7311 - loss: 0.5426 - val_accuracy: 0.8245 - val_loss: 0.4129
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4246 - val_accuracy: 0.8420 - val_loss: 0.3802
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8477 - loss: 0.3813 - val_accuracy: 0.8600 - val_loss: 0.3614
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8583 - loss: 0.3568 - val_accuracy: 0.8605 - val_loss: 0.3535
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8669 - loss: 0.3450 - val_accuracy: 0.8530 - val_loss: 0.3554
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8593 - loss: 0.3466 - val_accuracy: 0.8555 - val_loss: 0.3487
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8495 - loss: 0.3585 - val_accuracy: 0.8590 - val_loss: 0.3458
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8563 - loss: 0.3566 - val_accuracy: 0.8615 - val_loss: 0.3464
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8567 - loss: 0.3514 - val_accuracy: 0.8600 - val_loss: 0.3452
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3322 - val_accuracy: 0.8575 - val_loss: 0.3478
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8496 - loss: 0.3577 - val_accuracy: 0.8575 - val_loss: 0.3463
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8603 - loss: 0.3424 - val_accuracy: 0.8615 - val_loss: 0.3442
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8616 - loss: 0.3375 - val_accuracy: 0.8615 - val_loss: 0.3470
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8540 - loss: 0.3420 - val_accuracy: 0.8600 - val_loss: 0.3452
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8646 - loss: 0.3345 - val_accuracy: 0.8615 - val_loss: 0.3444
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8617 - loss: 0.3388 - val_accuracy: 0.8625 - val_loss: 0.3410
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8664 - loss: 0.3207 - val_accuracy: 0.8590 - val_loss: 0.3465
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8612 - loss: 0.3335 - val_accuracy: 0.8630 - val_loss: 0.3397
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8621 - loss: 0.3345 - val_accuracy: 0.8620 - val_loss: 0.3390
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3438 - val_accuracy: 0.8640 - val_loss: 0.3388
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy with Tanh activation: 86.40%

In [30]:
model_sigmoid = Sequential()


model_sigmoid.add(Dense(64, input_dim=X_train.shape[1], activation='sigmoid'))

model_sigmoid.add(Dense(32, activation='sigmoid'))


model_sigmoid.add(Dense(1, activation='sigmoid'))

model_sigmoid.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


history_sigmoid = model_sigmoid.fit(X_train_scaled, y_train, epochs=20, batch_size=32, validation_data=(X_test_scaled, y_test))

y_pred_sigmoid = (model_sigmoid.predict(X_test_scaled) > 0.5).astype(int)
accuracy_sigmoid = accuracy_score(y_test, y_pred_sigmoid)

print(f"Accuracy with Sigmoid in all layers: {accuracy_sigmoid * 100:.2f}%")
print("Confusion Matrix with Sigmoid in all layers:")
print(confusion_matrix(y_test, y_pred_sigmoid))

Epoch 1/20

C:\Users\Armaan\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7913 - loss: 0.5068 - val_accuracy: 0.8030 - val_loss: 0.4409
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7911 - loss: 0.4553 - val_accuracy: 0.8115 - val_loss: 0.4234
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8012 - loss: 0.4449 - val_accuracy: 0.8085 - val_loss: 0.4199
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8003 - loss: 0.4348 - val_accuracy: 0.8135 - val_loss: 0.4184
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7935 - loss: 0.4483 - val_accuracy: 0.8160 - val_loss: 0.4170
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8109 - loss: 0.4377 - val_accuracy: 0.8170 - val_loss: 0.4154
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8142 - loss: 0.4308 - val_accuracy: 0.8175 - val_loss: 0.4174
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8092 - loss: 0.4325 - val_accuracy: 0.8200 - val_loss: 0.4143
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8215 - loss: 0.4316 - val_accuracy: 0.8310 - val_loss: 0.4098
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8269 - loss: 0.4198 - val_accuracy: 0.8320 - val_loss: 0.4053
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8301 - loss: 0.4144 - val_accuracy: 0.8355 - val_loss: 0.4044
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.8351 - loss: 0.4153 - val_accuracy: 0.8390 - val_loss: 0.4022
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8298 - loss: 0.4127 - val_accuracy: 0.8410 - val_loss: 0.3982
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8246 - loss: 0.4254 - val_accuracy: 0.8425 - val_loss: 0.3945
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8392 - loss: 0.4021 - val_accuracy: 0.8420 - val_loss: 0.3927
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8325 - loss: 0.4071 - val_accuracy: 0.8450 - val_loss: 0.3863
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8317 - loss: 0.4029 - val_accuracy: 0.8405 - val_loss: 0.3891
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8454 - loss: 0.3873 - val_accuracy: 0.8445 - val_loss: 0.3764
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8473 - loss: 0.3806 - val_accuracy: 0.8515 - val_loss: 0.3732
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8469 - loss: 0.3795 - val_accuracy: 0.8475 - val_loss: 0.3659
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy with Sigmoid in all layers: 84.75%
Confusion Matrix with Sigmoid in all layers:
[[1569   38]
 [ 267  126]]